# Generated by Django 4.2.17 on 2025-01-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'ordering': ['-data_pubblicazione']},
        ),
    ]
