# Generated by Django 4.2.17 on 2025-01-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0007_remove_articolo_ora_pubblicazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcoountSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
    ]
