# Generated by Django 4.2.17 on 2025-01-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0009_rename_date_subscribed_acoountsubscriber_data_iscrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoountsubscriber',
            name='password',
            field=models.CharField(max_length=80),
        ),
    ]
