# Generated by Django 4.2.17 on 2025-01-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0010_alter_acoountsubscriber_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcoountSubscriber',
            new_name='AccountSubscriber',
        ),
    ]
