# Generated by Django 5.1.5 on 2025-01-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0010_alter_acoountsubscriber_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='descrizione_breve',
            field=models.TextField(default=''),
        ),
    ]
