# Generated by Django 4.2.17 on 2025-01-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0011_rename_acoountsubscriber_accountsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscriber',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
