# Generated by Django 4.2.17 on 2025-01-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0011_articolo_descrizione_breve'),
        ('articoli', '0012_alter_accountsubscriber_password'),
    ]

    operations = [
    ]
