# Generated by Django 2.2.12 on 2025-01-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0016_delete_accountsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='imagine',
            field=models.ImageField(blank=True, default='f.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mipiace',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
