# Generated by Django 2.2.12 on 2025-01-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0017_auto_20250129_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='imagine',
        ),
        migrations.CreateModel(
            name='ImmagineArticolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='articoli/')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='articoli.Articolo')),
            ],
        ),
    ]
