# Generated by Django 4.2.18 on 2025-02-05 20:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0021_alter_articolo_contenuto_alter_articolo_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='contenuto',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='descrizione_breve',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
