# Generated by Django 4.2.18 on 2025-03-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0022_alter_articolo_contenuto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiPiace',
        ),
    ]
