# Generated by Django 4.2.18 on 2025-03-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0023_delete_mipiace'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
