# Generated by Django 4.2.19 on 2025-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merch",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="Merch/"),
        ),
        migrations.AddField(
            model_name="merch",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="Merch/"),
        ),
        migrations.AddField(
            model_name="merch",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="Merch/"),
        ),
    ]
