# Generated by Django 4.2.19 on 2025-03-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merch", "0002_merch_image1_merch_image2_merch_image3"),
    ]

    operations = [
        migrations.AddField(
            model_name="merch",
            name="descrizione",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="merch",
            name="nome",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
