# Generated by Django 4.2.19 on 2025-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Merch", "0003_merch_descrizione_alter_merch_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="merch",
            name="prezzo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="merch",
            name="descrizione",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="merch",
            name="nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
