# Generated by Django 5.1.4 on 2025-01-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0002_alter_articolo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
