# Generated by Django 4.2.17 on 2025-01-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0006_articolo_ora_pubblicazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='ora_pubblicazione',
        ),
    ]
