# Generated by Django 4.2.17 on 2025-01-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0008_acoountsubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acoountsubscriber',
            old_name='date_subscribed',
            new_name='data_iscrizione',
        ),
    ]
