# Generated by Django 5.1.4 on 2025-01-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0014_mipiace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
