# Generated by Django 4.2.17 on 2025-01-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0015_delete_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountSubscriber',
        ),
    ]
