# Generated by Django 2.2.12 on 2025-01-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0018_auto_20250129_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='immagine',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImmagineArticolo',
        ),
    ]
