# Generated by Django 4.0.6 on 2025-02-25 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0022_alter_articolo_contenuto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mipiace',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mipiace',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mipiace',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='mipiace',
            name='articolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.articolo'),
        ),
        migrations.AlterUniqueTogether(
            name='mipiace',
            unique_together={('articolo', 'ip_address')},
        ),
        migrations.RemoveField(
            model_name='mipiace',
            name='utente',
        ),
    ]
