# Generated by Django 4.0.6 on 2025-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0023_alter_mipiace_unique_together_mipiace_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MiPiace',
        ),
    ]
