# Generated by Django 4.2.18 on 2025-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20250129_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
