# Generated by Django 4.2.18 on 2025-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountsubscriber_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('like', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountSubscriber',
        ),
    ]
