# Generated by Django 4.2.19 on 2025-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_account_delete_accountsubscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
