# Generated by Django 5.1.4 on 2025-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscrizionenewsletter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
